### ISSUE TITLE
Too small article view

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#240]
I don't know if this is your scope, but with a very small amount of text, the image gets cut off.

![auswahl_009](https://cloud.githubusercontent.com/assets/10520767/19251847/c4117fa6-8f41-11e6-916b-3bee2a403321.png)

**Comment by jangernert** [comment]
Maybe we should ask @bil-elmoussaoui.

**Comment by bil-elmoussaoui** [comment]
Can you give me the link of the article? or at least the html part of code so i can run some tests

**Comment by fb87** [comment]
http://www.golem.de/news/google-pixel-einiges-ist-fuer-telekom-kunden-anders-1610-123700.html

**Comment by jangernert** [comment]
Do you have the content-grabber deactivated? :P

**Comment by fb87** [comment]
No, I just set the dconf switch to kill the daemon when teh application is closed.

**Comment by bil-elmoussaoui** [comment]
I will investigate this and push a fix soon :+1:

**Comment by fb87** [comment]
This is another bug I encountered in master, which may have the same problem root:
![auswahl_001](https://cloud.githubusercontent.com/assets/10520767/20114527/f137334e-a5f4-11e6-917c-26007aa5aeb1.png)

It's due to this article:
https://www.heise.de/newsticker/meldung/Finnland-DDoS-Attacke-auf-Heizungssteuerung-3459730.html?wt_mc=rss.ho.beitrag.rdf

**Comment by bil-elmoussaoui** [comment]
@fb87 sorry for the delay. I will push a fix tomorrow evening! Thanks

**Comment by bil-elmoussaoui** [comment]
I couldn't get that article, can you somehow send me the html file of the page? just click on ctrl +S on your browser and either put the content of it here or email me at bil[dot]elmoussaoui[at]gmail[dot]com?

**Comment by fb87** [comment]
Hi, the first glitch got corrected in the meantime while the second issue still persists – nevertheless, here are both pages. Link works as soon as upload finishes.

https://dl.dropboxusercontent.com/u/327667/FR_bugs_pages.tar.xz

**Comment by bil-elmoussaoui** [comment]
@fb87 I couldn't find anything related to your screenshot on your html file. Use a SQLite manager to read your feedreader database (you will find it in `.local/share/feedreader/data/*.db` and look for the article using the search functionality. This will help you look for the article using the search by title of article, once it's done , copy the content of article and paste it here on github; 
I need the exact tags used here in order to fix it..

**Comment by fb87** [comment]
Upload hasn't even finished yet?

**Comment by bil-elmoussaoui** [comment]
Done on master!

**Comment by fbruetting** [comment]
Just tested the code – the second issue with the link reaching beyond the canvas still exists!

**Comment by fbruetting** [comment]
Even the first issue still exists (in some different way): The image is shown completely, but expands beyond the content frame.

http://www.golem.de/news/schwankende-laufzeiten-warentester-aendern-akku-bewertung-des-macbook-pro-1701-125558.html
![auswahl_001](https://cloud.githubusercontent.com/assets/10520767/21958279/37fe2914-daab-11e6-95e8-3b765f9bd496.png)

http://www.golem.de/news/compute-card-intel-plant-rechnermodul-mit-usb-type-c-1701-125560.html
![auswahl_002](https://cloud.githubusercontent.com/assets/10520767/21958283/418ac4ec-daab-11e6-82ad-5a8e20bd5642.png)

**Comment by bil-elmoussaoui** [comment]
Will fix it tomorrow

**Comment by fbruetting** [comment]
No hurry. ;)

**Comment by bil-elmoussaoui** [comment]
Just to keep you up to date; i've started rewriting the CSS file for the article themes and implementing this #299 ! I will try to fix every small issue with the CSS styling :)
