### ISSUE TITLE
No keyboard shortcuts, stable, Flatpak, Ubuntu 17.04

### ISSUE THREAD

**Issue by hopugop** [jangernert/FeedReader#489]
After FeedReader was installed via flatpak stable branch on Ubuntu 17.04, no keyboard shortcuts are working for navigation, only the arrow keys and PgUp/Dwn.

**Comment by jangernert** [comment]
already fixed in master

**Comment by qazip** [comment]
@jangernert , is it possible to install the master branch via flatpak? If so, how do I go about doing that?

**Comment by jscurtu** [comment]
@qazip the flathub package does not contain the master branch and it cannot because only stable releases are allowed.. We still have a separate flatpak repository, but I haven't updated the master branch in a very long time.. I might look in to doing so because I have to get it ready anyways...

**Comment by qazip** [comment]
Ya, it would be good to have the master branch. many bugs have been fixed since the latest release..
