### ISSUE TITLE
Translatable files do not reflect current state and source link broken.

### ISSUE THREAD

**Issue by comradekingu** [jangernert/FeedReader#630]
https://hosted.weblate.org/translate/feedreader/translations/nb/?checksum=6c953a511518d1b8

This still says "ownCloud", but it has been fixed here:

https://github.com/jangernert/FeedReader/blob/9dc46c160e6123852dcb902af13072c6b9b35e0f/plugins/backend/owncloud/OwncloudNewsInterface.vala#L167

Also, the right hand side Weblate link is broken:

https://github.com/angernert/FeedReader/blob/master/plugins/backend/owncloud/OwncloudNewsLoginWidget.vala#L161

**Comment by bil-elmoussaoui** [comment]
We should regenerate the pot file ;) I will take care of that right now!

**Comment by comradekingu** [comment]
@bil-elmoussaoui 
![source info](https://user-images.githubusercontent.com/13802408/35472190-fae7a7aa-036a-11e8-8759-9d12b29bc62d.png)

This is the link to the source file. It can be fixed in the Weblate settings.

**Comment by bil-elmoussaoui** [comment]
Should be fixed now

**Comment by comradekingu** [comment]
@bil-elmoussaoui Nice :) It is updated now. Link still broken.
I noticed another flaw in the link. It is /angernert on Weblate, when it should be /jangernert

**Comment by bil-elmoussaoui** [comment]
@brendanlong Can you please contact Weblate about that? We can't update the Github link anywhere on the settings, and I don't think it's the issue here, as weblate is able pull/push changes correctly. So it must be something else I guess....Anyway it's un upstream issue as far as I can tell

**Comment by comradekingu** [comment]
@bil-elmoussaoui I think it is where it says "repository browser" http://docs.weblate.org/en/latest/_images/add-component.png

http://docs.weblate.org/en/latest/admin/projects.html#component-configuration

**Comment by brendanlong** [comment]
@bilelmoussaoui  Sorry I just noticed this ticket. What do you need me to do?

**Comment by brendanlong** [comment]
Hm, it's not clear to me how we're supposed to make support requests, but I sent an email to the same place as when I set it up.

**Comment by bilelmoussaoui** [comment]
I have done the same for an issue I had with a project of mine. Issues can be opened here https://support.weblate.org/

**Comment by brendanlong** [comment]
I don't think I have a login for the support page :\

**Comment by bilelmoussaoui** [comment]
The issue was reported upstream. Hope it will be fixed as soon as possible. We can't do anything about it anyway

**Comment by brendanlong** [comment]
This is fixed
